# Generated by Django 2.2.1 on 2019-09-09 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=100)),
                ('Category', models.CharField(max_length=20)),
                ('Genre', models.CharField(max_length=20)),
                ('File', models.FileField(upload_to='')),
            ],
        ),
    ]
