# Generated by Django 2.2.1 on 2019-09-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='Author',
            field=models.CharField(default='', max_length=50),
        ),
    ]
